<?php

/**
 * hook_menu
 */
function room_expenditure_menu() {
  $items = [];
  $items['room_expenditure'] = [
    'page callback' => 'drupal_get_form',
    'page arguments' => array('room_expenditure'),
    'access callback' => TRUE,
  ];
  return $items;
}

/**
 * page callback
 */
function room_expenditure($from, &$form_state) {
  $from['fieldset'] = [
    '#type' => 'fieldset',
  ];
  $form_state['values']['count'] = empty($form_state['values']['count']) ? 1 : $form_state['values']['count'];
  for ($i = 0; $i < $form_state['values']['count']; $i++) {
    $form['fieldset'][$i]['top'] = [
      '#markup' => '<div class="field">'
    ];
    $form['fieldset'][$i]['amount'] = [
      '#type' => 'textfield',
      '#title' => t('Amount'),
    ];
    $form['fieldset'][$i]['sponsors'] = [
      '#type' => 'checkboxes',
      '#title' => t('Sponsors'),
    ];
    $form['fieldset'][$i]['contributors'] = [
      '#type' => 'Checkboxes',
      '#title' => t('Contributors'),
    ];
    $form['fieldset'][$i]['bottom'] = [
      '#markup' => '</div>'
    ];
  }
  $form['add'] = [
    '#type' => 'submit',
    '#ajax' => [
      'callback' => ['room_expenditure_add_callback'],
    ],
    '#submit' => ['room_expenditure_add'],
  ];
  $form['calculate'] = [
    '#type' => 'submit',
    '#ajax' => [
      'callback' => ['room_expenditure_calculate'],
    ],
  ];
  $form['calculations_wrapper'] = [
    '#markup' => '<div class="calculations-wrapper"></div>'
  ];
  return $form;
}

function room_expenditure_add_callback($from, &$form_state) {
  return $form['fieldset'];
}

function room_expenditure_add($from, &$form_state) {
  $form_state['values']['count']++;
  $form_state['rebuild'] = TRUE;
}